Add visual loading.. spinner to place order
Adyen/adyen-magento2-hyva pull request #68
Opened 2024-10-30 14:09 UTC by JustinElst

## Summary
It can take some time to process the place order wire, all the while the user does not know that a process is running.
This will add a loading spinner for the place order event.

2024-11-04 13:26 UTC, candemiralp requested changes

2024-11-04 13:26 UTC, candemiralp commented on view/frontend/templates/payment/model/adyen-payment-method.phtml
> +                    window.dispatchEvent(new Event('magewire:loader:done')
```suggestion
                    window.dispatchEvent(new Event('magewire:loader:done'));
```
Missing closing parenthesis causes exception.

2024-11-04 13:26 UTC, candemiralp commented on view/frontend/templates/payment/model/adyen-payment-method.phtml
> +                }).finish(() =>  {
```
checkout/:784 Uncaught (in promise) TypeError: wire.placeOrder(...).then(...).catch(...).finish is not a function
    at componentHandler.placeOrder (checkout/:784:20)
    at Object.placeOrder (checkout/:582:30)
    at checkout/:3560:70
    at async Proxy.onClick (checkout/:4102:25)
```

2024-11-04 13:27 UTC, candemiralp commented
Hello @JustinElst,

Thank you for your contribution. I've left a comment about an exception message that I got on my checkout. I've tried with 3DS2 and non 3DS2 card payments. Could you please elaborate on the issue?

Best Regards,
Can

2024-11-06 07:17 UTC, JustinElst commented on view/frontend/templates/payment/model/adyen-payment-method.phtml
> +                    window.dispatchEvent(new Event('magewire:loader:done')
This is fixed :) thanks.

2024-11-06 07:39 UTC, JustinElst commented
Thanks for your comments.
When a customer clicks the placeOrder button, a wire.placeOrder is triggered. This could take some time to in our case it does a round trip to the erp system to get a order-number. But in other cases with a slow internet or server this could take some time.

2024-11-07 14:04 UTC, candemiralp commented
**FYI CODEOWNERS**, the tests have been deployed locally and PR has passed the tests successfully.

2024-11-07 14:04 UTC, candemiralp approved these changes

2024-11-07 14:05 UTC, candemiralp commented
Hello @JustinElst,

Thank you for your contribution and fixing the issues on the PR. This improvement will be released after completing the code reviews.

Best Regards,
Can

2024-11-08 10:06 UTC, khushboo-singhvi approved these changes

2024-11-08 10:09 UTC, merged